#!/bin/bash

cmd=gdb
while getopts c: flag
do
    case "${flag}" in
        c) cmd=${OPTARG}; shift 2;;
    esac
done

tmux split-window -h
RIGHTDASHTTY=$(tmux display -p '#{pane_tty}')

tmux split-window -v -t 0
BELOWDASHTTY=$(tmux display -p '#{pane_tty}')

tmux select-pane -t 0
${cmd} \
    -ex "dashboard history -output $BELOWDASHTTY" \
    -ex "dashboard expressions -output $BELOWDASHTTY" \
    -ex "dashboard memory -output $BELOWDASHTTY" \
    -ex "dashboard threads -output $BELOWDASHTTY" \
    -ex "dashboard source -output $RIGHTDASHTTY" \
    -ex "dashboard stack -output $RIGHTDASHTTY" \
    -ex "dashboard assembly -output $RIGHTDASHTTY" \
    -ex "dashboard registers -output $RIGHTDASHTTY" \
    "$@"
tmux kill-pane -t 2
tmux kill-pane -t 1
