#!/bin/bash

tmux split-window -h
RIGHTDASHTTY=$(tmux display -pt 1 '#{pane_tty}')

tmux split-window -v -t 0
BELOWDASHTTY=$(tmux display -pt 2 '#{pane_tty}')

tmux select-pane -t 0
gdb \
    -ex "dashboard history -output $BELOWDASHTTY" \
    -ex "dashboard expressions -output $BELOWDASHTTY" \
    -ex "dashboard memory -output $BELOWDASHTTY" \
    -ex "dashboard source -output $RIGHTDASHTTY" \
    -ex "dashboard stack -output $RIGHTDASHTTY" \
    -ex "dashboard threads -output $RIGHTDASHTTY" \
    "$@"
tmux kill-pane -t 2
tmux kill-pane -t 1
